# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: 0.00
  joint_a2: 0.00
  joint_a3: 0.00
  joint_a4: 0.00
  joint_a5: 0.00
  joint_a6: 0.00
  joint_a7: 0.00
  left_finger_joint: 0.03
  right_finger_joint: -0.03
  

